## Queries

- Q1. What is the total sales revenue generated by BlinkIT?

SELECT ROUND(SUM(Sales), 2) AS Total_Sales
FROM BlinkIT;

- Q2. What is the average sales value across all transactions?

SELECT ROUND(AVG(Sales), 2) AS Avg_Sales
FROM BlinkIT;

- Q3. How many total items have been sold?

SELECT COUNT(*) AS No_of_Items
FROM BlinkIT;

- Q4. What is the average customer rating across all outlets?

SELECT ROUND(AVG(Rating), 2) AS Avg_Rating
FROM BlinkIT;

- Q5. How much sales revenue was generated by outlets established each year?

SELECT Outlet_Establishment_Year,
       ROUND(SUM(Sales), 2) AS Total_Sales
FROM BlinkIT
GROUP BY Outlet_Establishment_Year
ORDER BY Outlet_Establishment_Year;

- Q6. What is the sales distribution across different outlet sizes?

SELECT Outlet_Size,
       ROUND(SUM(Sales), 2) AS Total_Sales
FROM BlinkIT
GROUP BY Outlet_Size
ORDER BY Total_Sales DESC;

- Q7. Which outlet location type (Tier 1, Tier 2, Tier 3) contributes the most sales?

SELECT Outlet_Location_Type,
       ROUND(SUM(Sales), 2) AS Total_Sales
FROM BlinkIT
GROUP BY Outlet_Location_Type
ORDER BY Total_Sales DESC;


- Q8. Which item types have the highest number of products and sales?

SELECT Item_Type,
       COUNT(*) AS No_of_Items,
       ROUND(SUM(Sales), 2) AS Total_Sales
FROM BlinkIT
GROUP BY Item_Type
ORDER BY No_of_Items DESC;

- Q9. What is the distribution of items based on fat content (Low Fat vs Regular)?

SELECT Item_Fat_Content,
       COUNT(*) AS No_of_Items
FROM BlinkIT
GROUP BY Item_Fat_Content;

- Q10. How does fat content distribution vary across outlet locations?

SELECT Outlet_Location_Type,
       Item_Fat_Content,
       COUNT(*) AS No_of_Items
FROM BlinkIT
GROUP BY Outlet_Location_Type, Item_Fat_Content
ORDER BY Outlet_Location_Type;

- Q11. How do different outlet types perform in terms of sales, average sales, number of items, average rating, and visibility?

SELECT Outlet_Type,
       ROUND(SUM(Sales), 2) AS Total_Sales,
       ROUND(AVG(Sales), 2) AS Avg_Sales,
       COUNT(*) AS No_of_Items,
       ROUND(AVG(Rating), 2) AS Avg_Rating,
       ROUND(AVG(Item_Visibility), 2) AS Avg_Visibility
FROM BlinkIT
GROUP BY Outlet_Type
ORDER BY Total_Sales DESC;

